@startuml ArchitectureDiagram

  left to right direction

  actor User

  rectangle "DailyTrends ENV" {
    component "API DailyTrends" as API
    component "News Scraper" as Scraper
    database "MongoDB" as DB
  }
  rectangle "External Sources (Internet)" {
    node "El País Website" as ElPaisWS
    node "El Mundo Website" as ElMundoWS
  }
  
  User --> API : HTTP Requests
  API <--> DB : CRUD Ops (Feeds)
  API <--> Scraper : HTTP Requests
  Scraper --> ElPaisWS : Extract News (HTTP GET)
  Scraper --> ElMundoWS : Extract News (HTTP GET)

@enduml