@startuml DailyTrendsUseCases

  left to right direction

  actor User

  rectangle "DailyTrends" {
    
    User -- (View Daily Feeds)
    note right of (View Daily Feeds)
      Displays the top 5 headlines
      from 'El País' and 'El Mundo'
      for the current day.
    end note
    
    package "Feed Management (CRUD)" {
      User -- (Create Manual Feed)
      User -- (Create Multiple Feeds)
      User -- (View Feed)
      User -- (Update Feed)
      User -- (Delete Feed)
      User -- (List Feeds)
      (View Feed) ..> (Obtain Specific Feed) : <<include>>
      (Update Feed) ..> (Obtain Specific Feed) : <<include>>
      (Delete Feed) ..> (Obtain Specific Feed) : <<include>>
    }

  }

@enduml